api_platform:
    title: API CRM
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    use_symfony_listeners: true
    swagger:
        api-keys:
            JWT:
                name: Authorization
                type: header
        swagger_ui_extra_configuration:
            persistAuthorization: true
    formats:
        jsonld: ["application/ld+json"]
        json: [ "application/json" ]
        multipart: ['multipart/form-data']
